/*
DingusPPC - The Experimental PowerPC Macintosh emulator
Copyright (C) 2018-26 The DingusPPC Development Team
          (See CREDITS.MD for more details)

(You may also contact divingkxt or powermax2286 on Discord)

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

#include "atraps.h"

bool get_atrap_info(uint16_t trap, trap_info& trap_info) {
    switch (trap) {
    case 0x4E40: trap_info.name = "_TraceOn"; break;
    case 0x4E41: trap_info.name = "_TraceOff"; break;
    case 0x4E42: trap_info.name = "_DumpMemory"; break;
    case 0x4E43: trap_info.name = "_PutChar"; break;
    case 0x4E44: trap_info.name = "_PutString"; break;
    case 0xA000: trap_info.name = "_PBOpenSync"; break; // _Open
    case 0xA001: trap_info.name = "_PBCloseSync"; break; // _Close
    case 0xA002: trap_info.name = "_PBReadSync"; break; // _Read
    case 0xA003: trap_info.name = "_PBWriteSync"; break; // _Write
    case 0xA004: trap_info.name = "_PBControlSync"; break; // _Control
    case 0xA005: trap_info.name = "_PBStatusSync"; break; // _Status
    case 0xA006: trap_info.name = "_PBKillIOSync"; break; // _KillIO
    case 0xA007: trap_info.name = "_PBGetVInfoSync"; break; // _GetVolInfo
    case 0xA008: trap_info.name = "_PBCreateSync"; break; // _Create
    case 0xA009: trap_info.name = "_PBDeleteSync"; break; // _Delete
    case 0xA00A: trap_info.name = "_PBOpenRFSync"; break; // _OpenRF
    case 0xA00B: trap_info.name = "_PBRenameSync"; break; // _Rename, _ReName
    case 0xA00C: trap_info.name = "_PBGetFInfoSync"; break; // _GetFileInfo
    case 0xA00D: trap_info.name = "_PBSetFInfoSync"; break; // _SetFileInfo
    case 0xA00E: trap_info.name = "_PBUnmountVol"; break; // _UnmountVol, _UnMountVol
    case 0xA00F: trap_info.name = "_PBMountVol"; break; // _MountVol
    case 0xA010: trap_info.name = "_PBAllocateSync"; break; // _Allocate, _FileAllocate
    case 0xA011: trap_info.name = "_PBGetEOFSync"; break; // _GetEOF
    case 0xA012: trap_info.name = "_PBSetEOFSync"; break; // _SetEOF
    case 0xA013: trap_info.name = "_PBFlushVolSync"; break; // _FlushVol
    case 0xA014: trap_info.name = "_PBGetVolSync"; break; // _GetVol
    case 0xA015: trap_info.name = "_PBSetVolSync"; break; // _SetVol
    case 0xA016: trap_info.name = "_FInitQueue"; break; // _FInitQueue, _InitQueue
    case 0xA017: trap_info.name = "_PBEject"; break; // _Eject
    case 0xA018: trap_info.name = "_PBGetFPosSync"; break; // _GetFPos
    case 0xA019: trap_info.name = "_InitZone"; break;
    case 0xA01B: trap_info.name = "_SetZone"; break;
    case 0xA01C: trap_info.name = "_FreeMem"; break;
    case 0xA01F: trap_info.name = "_DisposePtr"; break; // _DisposPtr
    case 0xA020: trap_info.name = "_SetPtrSize"; break;
    case 0xA021: trap_info.name = "_GetPtrSize"; break;
    case 0xA023: trap_info.name = "_DisposeHandle"; break; // _DisposHandle
    case 0xA024: trap_info.name = "_SetHandleSize"; break;
    case 0xA025: trap_info.name = "_GetHandleSize"; break;
    case 0xA027: trap_info.name = "_ReallocateHandle"; break; // _ReAllocHandle, _ReallocHandle
    case 0xA029: trap_info.name = "_HLock"; break;
    case 0xA02A: trap_info.name = "_HUnlock"; break; // _HUnLock
    case 0xA02B: trap_info.name = "_EmptyHandle"; break;
    case 0xA02C: trap_info.name = "_InitApplZone"; break;
    case 0xA02D: trap_info.name = "_SetApplLimit"; break;
    case 0xA02E: trap_info.name = "_BlockMove"; break;
    case 0xA02F: trap_info.name = "_PostEvent"; break;
    case 0xA030: trap_info.name = "_OSEventAvail"; break;
    case 0xA031: trap_info.name = "_GetOSEvent"; break;
    case 0xA032: trap_info.name = "_FlushEvents"; break;
    case 0xA033: trap_info.name = "_VInstall"; break;
    case 0xA034: trap_info.name = "_VRemove"; break;
    case 0xA035: trap_info.name = "_PBOffLine"; break; // _OffLine, _Offline
    case 0xA036: trap_info.name = "_MoreMasters"; break;
    case 0xA037: trap_info.name = "_ReadParam"; break;
    case 0xA038: trap_info.name = "_WriteParam"; break;
    case 0xA039: trap_info.name = "_ReadDateTime"; break;
    case 0xA03A: trap_info.name = "_SetDateTime"; break;
    case 0xA03B: trap_info.name = "_Delay"; break;
    case 0xA03C: trap_info.name = "_CmpString"; break;
    case 0xA03D: trap_info.name = "_DriverInstall"; break; // _DrvrInstall
    case 0xA03E: trap_info.name = "_DrvrRemove"; break;
    case 0xA03F: trap_info.name = "_InitUtil"; break;
    case 0xA040: trap_info.name = "_ReserveMem"; break; // _ResrvMem, _ReserveMem
    case 0xA041: trap_info.name = "_PBSetFLockSync"; break; // _SetFilLock
    case 0xA042: trap_info.name = "_PBRstFLockSync"; break; // RstFilLock
    case 0xA043: trap_info.name = "_PBSetFVersSync"; break; // _SetFilType
    case 0xA044: trap_info.name = "_PBSetFPosSync"; break; // _SetFPos
    case 0xA045: trap_info.name = "_PBFlushFileSync"; break; // _FlushFile
    case 0xA047: trap_info.name = "_SetTrapAddress"; break;
    case 0xA049: trap_info.name = "_HPurge"; break;
    case 0xA04A: trap_info.name = "_HNoPurge"; break;
    case 0xA04B: trap_info.name = "_SetGrowZone"; break;
    case 0xA04C: trap_info.name = "_CompactMem"; break;
    case 0xA04D: trap_info.name = "_PurgeMem"; break;
    case 0xA04E: trap_info.name = "_AddDrive"; break;
    case 0xA04F: trap_info.name = "_RDrvrInstall"; break;
    case 0xA050: trap_info.name = "_RelString"; break; // _CompareString
    case 0xA051: trap_info.name = "_ReadXPRam"; break;
    case 0xA052: trap_info.name = "_WriteXPRam"; break;
    case 0xA053: trap_info.name = "_ClkNoMem"; break;
    case 0xA054: trap_info.name = "_UpperString"; break; // _UprString, UprText
    case 0xA055: trap_info.name = "_StripAddress"; break;
    case 0xA056: trap_info.name = "_LowerText"; break; // _LwrText, _LwrString
    case 0xA057: trap_info.name = "_SetApplBase"; break; // _SetAppBase
    case 0xA058: trap_info.name = "_InstallTimeTask"; break; // _InsTime
    case 0xA059: trap_info.name = "_RemoveTimeTask"; break; // _RmvTime
    case 0xA05A: trap_info.name = "_PrimeTimeTask"; break; // _PrimeTime
    case 0xA05B: trap_info.name = "_PowerOff"; break;
    case 0xA05C: trap_info.name = "_MemoryDispatch"; break;
    case 0xA05D: trap_info.name = "_SwapMMUMode"; break;
    case 0xA05E: trap_info.name = "_NMInstall"; break; // _SetMMUmode
    case 0xA05F: trap_info.name = "_NMRemove"; break; // _RestoreMMUmode
    case 0xA060: trap_info.name = "_FSDispatch"; break;
    case 0xA061: trap_info.name = "_MaxBlock"; break;
    case 0xA062: trap_info.name = "_PurgeSpace"; break; // D0 _PurgeSpaceContiguous, A0 _PurgeSpaceTotal
    case 0xA063: trap_info.name = "_MaxApplZone"; break;
    case 0xA064: trap_info.name = "_MoveHHi"; break;
    case 0xA065: trap_info.name = "_StackSpace"; break;
    case 0xA067: trap_info.name = "_HSetRBit"; break;
    case 0xA068: trap_info.name = "_HClrRBit"; break;
    case 0xA069: trap_info.name = "_HGetState"; break;
    case 0xA06A: trap_info.name = "_HSetState"; break;
    case 0xA06B: trap_info.name = "_TestManager"; break;
    case 0xA06C: trap_info.name = "_InitFS"; break;
    case 0xA06D: trap_info.name = "_InitEvents"; break;
    case 0xA06E: trap_info.name = "_SlotManager"; break;
    case 0xA06F: trap_info.name = "_SlotVInstall"; break;
    case 0xA070: trap_info.name = "_SlotVRemove"; break;
    case 0xA071: trap_info.name = "_AttachVBL"; break;
    case 0xA072: trap_info.name = "_DoVBLTask"; break;
    case 0xA073: trap_info.name = "_OSReserved"; break;
    case 0xA074: trap_info.name = "_CacheMgr"; break; // _Cache
    case 0xA075: trap_info.name = "_SIntInstall"; break;
    case 0xA076: trap_info.name = "_SIntRemove"; break;
    case 0xA077: trap_info.name = "_CountADBs"; break;
    case 0xA078: trap_info.name = "_GetIndADB"; break;
    case 0xA079: trap_info.name = "_GetADBInfo"; break;
    case 0xA07A: trap_info.name = "_SetADBInfo"; break;
    case 0xA07B: trap_info.name = "_ADBReInit"; break;
    case 0xA07C: trap_info.name = "_ADBOp"; break;
    case 0xA07D: trap_info.name = "_GetDefaultStartup"; break;
    case 0xA07E: trap_info.name = "_SetDefaultStartup"; break;
    case 0xA07F: trap_info.name = "_InternalWait"; break;
    case 0xA080: trap_info.name = "_GetVideoDefault"; break;
    case 0xA081: trap_info.name = "_SetVideoDefault"; break;
    case 0xA082: trap_info.name = "_DTInstall"; break;
    case 0xA083: trap_info.name = "_SetOSDefault"; break;
    case 0xA084: trap_info.name = "_GetOSDefault"; break;
    case 0xA085: trap_info.name = "_PMgrOp"; break; // _PmgrOp
    case 0xA086: trap_info.name = "_IOPInfoAccess"; break;
    case 0xA087: trap_info.name = "_IOPMsgRequest"; break;
    case 0xA088: trap_info.name = "_IOPMoveData"; break;
    case 0xA089: trap_info.name = "_SCSIAtomic"; break; // _NewSCSI
    case 0xA08A: trap_info.name = "_Sleep"; break;
    case 0xA08B: trap_info.name = "_CommToolboxDispatch"; break;
    case 0xA08C: trap_info.name = "_Wakeup"; break;
    case 0xA08D: trap_info.name = "_DebugUtil"; break;
    case 0xA08E: trap_info.name = "_BTreeDispatch"; break;
    case 0xA08F: trap_info.name = "_DeferUserFn"; break; // _Deferred
    case 0xA090: trap_info.name = "_SysEnvirons"; break;
    case 0xA091: trap_info.name = "_Translate24To32"; break;
    case 0xA092: trap_info.name = "_EgretDispatch"; break; // _Egret
    case 0xA093: trap_info.name = "_Microseconds"; break;
    case 0xA094: trap_info.name = "_ServerDispatch"; break;
    case 0xA095: trap_info.name = "_POGOMPW"; break;
    case 0xA096: trap_info.name = "_SharedLibsMPW"; break;
    case 0xA097: trap_info.name = "_FPPriv"; break;
    case 0xA099: trap_info.name = "_XToolTable"; break;
    case 0xA09A: trap_info.name = "_vProcHelper"; break; // _ProcHelperTrap
    case 0xA09B: trap_info.name = "_Messager"; break;
    case 0xA09C: trap_info.name = "_NewPtrStartup"; break;
    case 0xA09D: trap_info.name = "_MoveHLow"; break;
    case 0xA09E: trap_info.name = "_PowerMgrDispatch"; break;
    case 0xA09F: trap_info.name = "_PowerDispatch"; break;
    case 0xA0A0: trap_info.name = "_vMRdAddr"; break;
    case 0xA0A1: trap_info.name = "_vMRdData"; break;
    case 0xA0A2: trap_info.name = "_vMWrData"; break;
    case 0xA0A4: trap_info.name = "_HeapDispatch"; break; // _FigmentDispatch
    case 0xA0A5: trap_info.name = "_VisRegionChanged"; break;
    case 0xA0A6: trap_info.name = "_vStdEntry"; break;
    case 0xA0A7: trap_info.name = "_vStdExit"; break;
    case 0xA0AC: trap_info.name = "_FSMDispatch"; break; // _FSM
    case 0xA0AE: trap_info.name = "_vADBProc"; break;
    case 0xA0AF: trap_info.name = "_vMtCheck"; break;
    case 0xA0B0: trap_info.name = "_vCheckReMount"; break;
    case 0xA0B1: trap_info.name = "_vDtrmV2"; break;
    case 0xA0B2: trap_info.name = "_vFindDrive"; break;
    case 0xA0B3: trap_info.name = "_vFClose"; break;
    case 0xA0B4: trap_info.name = "_vFlushMDB"; break;
    case 0xA0B5: trap_info.name = "_vGoDriver"; break;
    case 0xA0B6: trap_info.name = "_vWaitUntil"; break;
    case 0xA0B7: trap_info.name = "_vSyncWait"; break;
    case 0xA0B8: trap_info.name = "_vSoundDead"; break; // _SndAppDead
    case 0xA0B9: trap_info.name = "_vDisptch"; break; // _vDisPtch
    case 0xA0BA: trap_info.name = "_vIAZInit"; break;
    case 0xA0BB: trap_info.name = "_vIAZPostInit"; break;
    case 0xA0BC: trap_info.name = "_vLaunchInit"; break;
    case 0xA0BD: trap_info.name = "_FlushCodeCache"; break; // _vCacheFlush
    case 0xA0BE: trap_info.name = "_vSysUtil"; break;
    case 0xA0BF: trap_info.name = "_vLg2Phys"; break;
    case 0xA0C0: trap_info.name = "_vFlushCache"; break;
    case 0xA0C1: trap_info.name = "_vGetBlock"; break;
    case 0xA0C2: trap_info.name = "_vMarkBlock"; break;
    case 0xA0C3: trap_info.name = "_vRelBlock"; break;
    case 0xA0C4: trap_info.name = "_vTrashBlocks"; break;
    case 0xA0C5: trap_info.name = "_vTrashVBlks"; break;
    case 0xA0C6: trap_info.name = "_vCacheWrIP"; break;
    case 0xA0C7: trap_info.name = "_vCacheRdIP"; break;
    case 0xA0C8: trap_info.name = "_vBasicIO"; break;
    case 0xA0C9: trap_info.name = "_vRdBlocks"; break;
    case 0xA0CA: trap_info.name = "_vWrBlocks"; break;
    case 0xA0CB: trap_info.name = "_vSetUpTags"; break;
    case 0xA0CC: trap_info.name = "_vBTClose"; break;
    case 0xA0CD: trap_info.name = "_vBTDelete"; break;
    case 0xA0CE: trap_info.name = "_vBTFlush"; break;
    case 0xA0CF: trap_info.name = "_vBTGetRecord"; break;
    case 0xA0D0: trap_info.name = "_vBTInsert"; break;
    case 0xA0D1: trap_info.name = "_vBTOpen"; break;
    case 0xA0D2: trap_info.name = "_vBTSearch"; break;
    case 0xA0D3: trap_info.name = "_vBTUpdate"; break;
    case 0xA0D4: trap_info.name = "_vGetNode"; break;
    case 0xA0D5: trap_info.name = "_vRelNode"; break;
    case 0xA0D6: trap_info.name = "_vAllocNode"; break;
    case 0xA0D7: trap_info.name = "_vFreeNode"; break;
    case 0xA0D8: trap_info.name = "_vExtBTFile"; break;
    case 0xA0D9: trap_info.name = "_vDeallocFile"; break;
    case 0xA0DA: trap_info.name = "_vExtendFile"; break;
    case 0xA0DB: trap_info.name = "_vTruncateFile"; break;
    case 0xA0DC: trap_info.name = "_vCMSetup"; break; // _vCMSetUp
    case 0xA0DD: trap_info.name = "_PPC"; break;
    case 0xA0DE: trap_info.name = "_vDtrmV1"; break;
    case 0xA0DF: trap_info.name = "_vBlkAlloc"; break;
    case 0xA0E0: trap_info.name = "_vBlkDeAlloc"; break;
    case 0xA0E1: trap_info.name = "_vFileOpen"; break;
    case 0xA0E2: trap_info.name = "_vPermssnChk"; break;
    case 0xA0E3: trap_info.name = "_vFndFilName"; break;
    case 0xA0E4: trap_info.name = "_vRfNCall"; break;
    case 0xA0E5: trap_info.name = "_vAdjEOF"; break;
    case 0xA0E6: trap_info.name = "_vPixel2Char"; break;
    case 0xA0E7: trap_info.name = "_vChar2Pixel"; break;
    case 0xA0E8: trap_info.name = "_vHiliteText"; break;
    case 0xA0E9: trap_info.name = "_vFileClose"; break;
    case 0xA0EA: trap_info.name = "_vFileRead"; break;
    case 0xA0EB: trap_info.name = "_vFileWrite"; break;
    case 0xA0EC: trap_info.name = "_DispatchHelper"; break; // _DispatchHelperTrap
    case 0xA0ED: trap_info.name = "_vUpdAltMDB"; break;
    case 0xA0EE: trap_info.name = "_vCkExtFS"; break; // _vCkExtFs
    case 0xA0EF: trap_info.name = "_vDtrmV3"; break;
    case 0xA0F0: trap_info.name = "_vBMChk"; break;
    case 0xA0F1: trap_info.name = "_vTstMod"; break;
    case 0xA0F2: trap_info.name = "_vLocCRec"; break;
    case 0xA0F3: trap_info.name = "_vTreeSearch"; break;
    case 0xA0F4: trap_info.name = "_vMapFBlock"; break;
    case 0xA0F5: trap_info.name = "_vXFSearch"; break;
    case 0xA0F6: trap_info.name = "_vReadBM"; break;
    case 0xA0F7: trap_info.name = "_vDoEject"; break;
    case 0xA0F8: trap_info.name = "_vSegStack"; break;
    case 0xA0F9: trap_info.name = "_vSuperLoad"; break;
    case 0xA0FA: trap_info.name = "_vCmpFrm"; break;
    case 0xA0FB: trap_info.name = "_vNewMap"; break;
    case 0xA0FC: trap_info.name = "_vCheckLoad"; break;
    case 0xA0FD: trap_info.name = "_XTrimMeasure"; break;
    case 0xA0FE: trap_info.name = "_TEFindWord"; break; // _XFindWord
    case 0xA0FF: trap_info.name = "_TEFindLine"; break; // _XFindLine
    case 0xA11A: trap_info.name = "_GetZone"; break;
    case 0xA11D: trap_info.name = "_MaxMem"; break;
    case 0xA11E: trap_info.name = "_NewPtr"; break;
    case 0xA122: trap_info.name = "_NewHandle"; break;
    case 0xA126: trap_info.name = "_HandleZone"; break;
    case 0xA128: trap_info.name = "_RecoverHandle"; break;
    case 0xA12F: trap_info.name = "_PPostEvent"; break;
    case 0xA13D: trap_info.name = "_DrvrInstall"; break;
    case 0xA146: trap_info.name = "_GetTrapAddress"; break;
    case 0xA148: trap_info.name = "_PtrZone"; break;
    case 0xA15C: trap_info.name = "_MemoryDispatch"; break; // _MemoryDispatchA0Result
    case 0xA162: trap_info.name = "_PurgeSpace"; break;
    case 0xA166: trap_info.name = "_NewEmptyHandle"; break;
    case 0xA193: trap_info.name = "_Microseconds"; break; // _GetMicroSeconds
    case 0xA198: trap_info.name = "_HWPriv"; break; // _HwPriv
    case 0xA1AD: trap_info.name = "_Gestalt"; break;
    case 0xA200: trap_info.name = "_PBHOpenSync"; break; // :Files, PBOpenImmed:Devices, _OpenSlotSync:Slots, _HOpen:Traps
    case 0xA201: trap_info.name = "_PBCloseImmed"; break;
    case 0xA202: trap_info.name = "_PBReadImmed"; break;
    case 0xA203: trap_info.name = "_PBWriteImmed"; break;
    case 0xA204: trap_info.name = "_PBControlImmed"; break;
    case 0xA205: trap_info.name = "_PBStatusImmed"; break;
    case 0xA206: trap_info.name = "_PBKillIOImmed"; break;
    case 0xA207: trap_info.name = "_PBHGetVInfoSync"; break; // _HGetVInfo
    case 0xA208: trap_info.name = "_PBHCreateSync"; break; // _HCreate
    case 0xA209: trap_info.name = "_PBHDeleteSync"; break; // _HDelete
    case 0xA20A: trap_info.name = "_PBHOpenRFSync"; break; // _HOpenRF
    case 0xA20B: trap_info.name = "_PBHRenameSync"; break; // _HRename
    case 0xA20C: trap_info.name = "_PBHGetFInfoSync"; break; // _HGetFileInfo
    case 0xA20D: trap_info.name = "_PBHSetFInfoSync"; break; // _HSetFileInfo
    case 0xA20E: trap_info.name = "_PBUnmountVolImmed"; break; // _HUnmountVol
    case 0xA210: trap_info.name = "_PBAllocContigSync"; break; // _AllocContig
    case 0xA212: trap_info.name = "_SetPEOF"; break;
    case 0xA213: trap_info.name = "_PBHTrashVolumeCachesSync"; break;
    case 0xA214: trap_info.name = "_PBHGetVolSync"; break; // _HGetVol
    case 0xA215: trap_info.name = "_PBHSetVolSync"; break; // _HSetVol
    case 0xA22E: trap_info.name = "_BlockMoveData"; break;
    case 0xA23C: trap_info.name = "_CmpStringMarks"; break; // _MarkSensitiveEqualString
    case 0xA241: trap_info.name = "_PBHSetFLockSync"; break; // _HSetFLock
    case 0xA242: trap_info.name = "_PBHRstFLockSync"; break; // _HRstFLock
    case 0xA247: trap_info.name = "_SetOSTrapAddress"; break;
    case 0xA250: trap_info.name = "_RelStringMarks"; break;
    case 0xA254: trap_info.name = "_UpperStringMarks"; break;
    case 0xA256: trap_info.name = "_StripText"; break;
    case 0xA260: trap_info.name = "_HFSDispatch"; break;
    case 0xA285: trap_info.name = "_IdleUpdate"; break;
    case 0xA28A: trap_info.name = "_SleepQInstall"; break; // _SlpQInstall
    case 0xA31E: trap_info.name = "_NewPtrClear"; break;
    case 0xA322: trap_info.name = "_NewHandleClear"; break;
    case 0xA346: trap_info.name = "_GetOSTrapAddress"; break;
    case 0xA3AD: trap_info.name = "_NewGestalt"; break;
    case 0xA400: trap_info.name = "_PBOpenAsync"; break;
    case 0xA401: trap_info.name = "_PBCloseAsync"; break;
    case 0xA402: trap_info.name = "_PBReadAsync"; break;
    case 0xA403: trap_info.name = "_PBWriteAsync"; break;
    case 0xA404: trap_info.name = "_PBControlAsync"; break;
    case 0xA405: trap_info.name = "_PBStatusAsync"; break;
    case 0xA406: trap_info.name = "_PBKillIOAsync"; break;
    case 0xA407: trap_info.name = "_PBGetVInfoAsync"; break;
    case 0xA408: trap_info.name = "_PBCreateAsync"; break;
    case 0xA409: trap_info.name = "_PBDeleteAsync"; break;
    case 0xA40A: trap_info.name = "_PBOpenRFAsync"; break;
    case 0xA40B: trap_info.name = "_PBRenameAsync"; break;
    case 0xA40C: trap_info.name = "_PBGetFInfoAsync"; break;
    case 0xA40D: trap_info.name = "_PBSetFInfoAsync"; break;
    case 0xA410: trap_info.name = "_PBAllocateAsync"; break;
    case 0xA411: trap_info.name = "_PBGetEOFAsync"; break;
    case 0xA412: trap_info.name = "_PBSetEOFAsync"; break;
    case 0xA413: trap_info.name = "_PBFlushVolAsync"; break;
    case 0xA414: trap_info.name = "_PBGetVolAsync"; break;
    case 0xA415: trap_info.name = "_PBSetVolAsync"; break;
    case 0xA418: trap_info.name = "_PBGetFPosAsync"; break;
    case 0xA41C: trap_info.name = "_FreeMemSys"; break;
    case 0xA427: trap_info.name = "_ReallocateHandleSys"; break;
    case 0xA43C: trap_info.name = "_CmpStringCase"; break; // _CaseSensitiveEqualString
    case 0xA43D: trap_info.name = "_DriverInstallReserveMem"; break; // _DrvrInstallRsrvMem
    case 0xA440: trap_info.name = "_ReserveMemSys"; break;
    case 0xA441: trap_info.name = "_PBSetFLockAsync"; break;
    case 0xA442: trap_info.name = "_PBRstFLockAsync"; break;
    case 0xA443: trap_info.name = "_PBSetFVersAsync"; break;
    case 0xA444: trap_info.name = "_PBSetFPosAsync"; break;
    case 0xA445: trap_info.name = "_PBFlushFileAsync"; break;
    case 0xA447: trap_info.name = "_SetTrapWordAddress"; break;
    case 0xA44C: trap_info.name = "_CompactMemSys"; break;
    case 0xA44D: trap_info.name = "_PurgeMemSys"; break;
    case 0xA450: trap_info.name = "_RelStringCase"; break;
    case 0xA456: trap_info.name = "_UpperText"; break;
    case 0xA458: trap_info.name = "_InstallXTimeTask"; break; // _InsXTime
    case 0xA460: trap_info.name = "_FSDispatchAsync"; break;
    case 0xA461: trap_info.name = "_MaxBlockSys"; break;
    case 0xA485: trap_info.name = "_IdleState"; break;
    case 0xA48A: trap_info.name = "_SleepQRemove"; break; // _SlpQRemove
    case 0xA4DD: trap_info.name = "_PPCAsync"; break;
    case 0xA51D: trap_info.name = "_MaxMemSys"; break;
    case 0xA51E: trap_info.name = "_NewPtrSys"; break;
    case 0xA522: trap_info.name = "_NewHandleSys"; break;
    case 0xA528: trap_info.name = "_RecoverHandleSys"; break;
    case 0xA53D: trap_info.name = "_DrvrInstallRsrvMem"; break;
    case 0xA546: trap_info.name = "_GetTrapWordAddress"; break;
    case 0xA562: trap_info.name = "_PurgeSpaceSys"; break; // D0 _PurgeSpaceSysContiguous, A0 _PurgeSpaceSysTotal
    case 0xA566: trap_info.name = "_NewEmptyHandleSys"; break;
    case 0xA5AD: trap_info.name = "_ReplaceGestalt"; break;
    case 0xA600: trap_info.name = "_PBHOpenAsync"; break; // Files:_PBHOpenAsync Slots:_OpenSlotAsync
    case 0xA607: trap_info.name = "_PBHGetVInfoAsync"; break;
    case 0xA608: trap_info.name = "_PBHCreateAsync"; break;
    case 0xA609: trap_info.name = "_PBHDeleteAsync"; break;
    case 0xA60A: trap_info.name = "_PBHOpenRFAsync"; break;
    case 0xA60B: trap_info.name = "_PBHRenameAsync"; break;
    case 0xA60C: trap_info.name = "_PBHGetFInfoAsync"; break;
    case 0xA60D: trap_info.name = "_PBHSetFInfoAsync"; break;
    case 0xA610: trap_info.name = "_PBAllocContigAsync"; break;
    case 0xA614: trap_info.name = "_PBHGetVolAsync"; break;
    case 0xA615: trap_info.name = "_PBHSetVolAsync"; break;
    case 0xA63C: trap_info.name = "_CmpStringMarksCase"; break; // _CaseAndMarkSensitiveEqualString
    case 0xA641: trap_info.name = "_PBHSetFLockAsync"; break;
    case 0xA642: trap_info.name = "_PBHRstFLockAsync"; break;
    case 0xA647: trap_info.name = "_SetToolboxTrapAddress"; break; // _SetToolTrapAddress, _SetToolBoxTrapAddress
    case 0xA650: trap_info.name = "_RelStringMarksCase"; break;
    case 0xA656: trap_info.name = "_StripUpperText"; break;
    case 0xA660: trap_info.name = "_HFSDispatchAsync"; break;
    case 0xA685: trap_info.name = "_SerialPower"; break;
    case 0xA71E: trap_info.name = "_NewPtrSysClear"; break;
    case 0xA722: trap_info.name = "_NewHandleSysClear"; break;
    case 0xA746: trap_info.name = "_GetToolboxTrapAddress"; break; // _GetToolTrapAddress, _GetToolBoxTrapAddress
    case 0xA7AD: trap_info.name = "_GetGestaltProcPtr"; break;
    case 0xA800: trap_info.name = "_SoundDispatch"; break;
    case 0xA801: trap_info.name = "_SndDisposeChannel"; break;
    case 0xA802: trap_info.name = "_SndAddModifier"; break;
    case 0xA803: trap_info.name = "_SndDoCommand"; break;
    case 0xA804: trap_info.name = "_SndDoImmediate"; break;
    case 0xA805: trap_info.name = "_SndPlay"; break;
    case 0xA806: trap_info.name = "_SndControl"; break;
    case 0xA807: trap_info.name = "_SndNewChannel"; break;
    case 0xA808: trap_info.name = "_InitProcMenu"; break;
    case 0xA809: trap_info.name = "_GetControlVariant"; break; // _GetCVariant
    case 0xA80A: trap_info.name = "_GetWVariant"; break;
    case 0xA80B: trap_info.name = "_PopUpMenuSelect"; break;
    case 0xA80C: trap_info.name = "_RGetResource"; break; // _rGetResource
    case 0xA80D: trap_info.name = "_Count1Resources"; break;
    case 0xA80E: trap_info.name = "_Get1IndResource"; break; // _Get1IxResource
    case 0xA80F: trap_info.name = "_Get1IndType"; break; // _Get1IxType
    case 0xA810: trap_info.name = "_Unique1ID"; break;
    case 0xA811: trap_info.name = "_TESelView"; break;
    case 0xA812: trap_info.name = "_TEPinScroll"; break;
    case 0xA813: trap_info.name = "_TEAutoView"; break;
    case 0xA814: trap_info.name = "_SetFractEnable"; break;
    case 0xA815: trap_info.name = "_SCSIDispatch"; break;
    case 0xA816: trap_info.name = "_Pack8"; break;
    case 0xA817: trap_info.name = "_CopyMask"; break;
    case 0xA818: trap_info.name = "_FixATan2"; break; // _FixAtan2
    case 0xA819: trap_info.name = "_XMunger"; break;
    case 0xA81A: trap_info.name = "_HOpenResFile"; break;
    case 0xA81B: trap_info.name = "_HCreateResFile"; break;
    case 0xA81C: trap_info.name = "_Count1Types"; break;
    case 0xA81D: trap_info.name = "_InvalMenuBar"; break;
    case 0xA81E: trap_info.name = "_SaveRestoreBits"; break;
    case 0xA81F: trap_info.name = "_Get1Resource"; break;
    case 0xA820: trap_info.name = "_Get1NamedResource"; break;
    case 0xA821: trap_info.name = "_GetMaxResourceSize"; break; // _MaxSizeRsrc
    case 0xA822: trap_info.name = "_ResourceDispatch"; break;
    case 0xA823: trap_info.name = "_AliasDispatch"; break;
    case 0xA824: trap_info.name = "_HFSUtilDispatch"; break; // _FSMgr, _HFSUtil
    case 0xA825: trap_info.name = "_MenuDispatch"; break;
    case 0xA826: trap_info.name = "_InsertMenuItem"; break; // _InsMenuItem
    case 0xA827: trap_info.name = "_HideDialogItem"; break; // _HideDItem
    case 0xA828: trap_info.name = "_ShowDialogItem"; break; // _ShowDItem
    case 0xA829: trap_info.name = "_LayerDispatch"; break;
    case 0xA82A: trap_info.name = "_ComponentDispatch"; break;
    case 0xA82B: trap_info.name = "_Pack9"; break;
    case 0xA82C: trap_info.name = "_Pack10"; break;
    case 0xA82D: trap_info.name = "_Pack11"; break;
    case 0xA82E: trap_info.name = "_Pack12"; break;
    case 0xA82F: trap_info.name = "_Pack13"; break;
    case 0xA830: trap_info.name = "_Pack14"; break;
    case 0xA831: trap_info.name = "_Pack15"; break;
    case 0xA832: trap_info.name = "_QuickDrawGX"; break;
    case 0xA833: trap_info.name = "_ScrnBitMap"; break;
    case 0xA834: trap_info.name = "_SetFScaleDisable"; break;
    case 0xA835: trap_info.name = "_FontMetrics"; break;
    case 0xA836: trap_info.name = "_GetMaskTable"; break;
    case 0xA837: trap_info.name = "_MeasureText"; break;
    case 0xA838: trap_info.name = "_CalcMask"; break;
    case 0xA839: trap_info.name = "_SeedFill"; break;
    case 0xA83A: trap_info.name = "_ZoomWindow"; break;
    case 0xA83B: trap_info.name = "_TrackBox"; break;
    case 0xA83C: trap_info.name = "_TEGetOffset"; break;
    case 0xA83D: trap_info.name = "_TEDispatch"; break;
    case 0xA83E: trap_info.name = "_TEStyleNew"; break;
    case 0xA83F: trap_info.name = "_Long2Fix"; break;
    case 0xA840: trap_info.name = "_Fix2Long"; break;
    case 0xA841: trap_info.name = "_Fix2Frac"; break;
    case 0xA842: trap_info.name = "_Frac2Fix"; break;
    case 0xA843: trap_info.name = "_Fix2X"; break;
    case 0xA844: trap_info.name = "_X2Fix"; break;
    case 0xA845: trap_info.name = "_Frac2X"; break;
    case 0xA846: trap_info.name = "_X2Frac"; break;
    case 0xA847: trap_info.name = "_FracCos"; break;
    case 0xA848: trap_info.name = "_FracSin"; break;
    case 0xA849: trap_info.name = "_FracSqrt"; break;
    case 0xA84A: trap_info.name = "_FracMul"; break;
    case 0xA84B: trap_info.name = "_FracDiv"; break;
    case 0xA84C: trap_info.name = "_UserDelay"; break;
    case 0xA84D: trap_info.name = "_FixDiv"; break;
    case 0xA84E: trap_info.name = "_GetItemCmd"; break;
    case 0xA84F: trap_info.name = "_SetItemCmd"; break;
    case 0xA850: trap_info.name = "_InitCursor"; break;
    case 0xA851: trap_info.name = "_SetCursor"; break;
    case 0xA852: trap_info.name = "_HideCursor"; break;
    case 0xA853: trap_info.name = "_ShowCursor"; break;
    case 0xA854: trap_info.name = "_FontDispatch"; break; // _SplineCall, _SplineMgr
    case 0xA855: trap_info.name = "_ShieldCursor"; break;
    case 0xA856: trap_info.name = "_ObscureCursor"; break;
    case 0xA857: trap_info.name = "_SetEntry"; break;
    case 0xA858: trap_info.name = "_BitAnd"; break;
    case 0xA859: trap_info.name = "_BitXor"; break; // _BitXOr
    case 0xA85A: trap_info.name = "_BitNot"; break;
    case 0xA85B: trap_info.name = "_BitOr"; break;
    case 0xA85C: trap_info.name = "_BitShift"; break;
    case 0xA85D: trap_info.name = "_BitTst"; break;
    case 0xA85E: trap_info.name = "_BitSet"; break;
    case 0xA85F: trap_info.name = "_BitClr"; break;
    case 0xA860: trap_info.name = "_WaitNextEvent"; break;
    case 0xA861: trap_info.name = "_Random"; break;
    case 0xA862: trap_info.name = "_ForeColor"; break;
    case 0xA863: trap_info.name = "_BackColor"; break;
    case 0xA864: trap_info.name = "_ColorBit"; break;
    case 0xA865: trap_info.name = "_GetPixel"; break;
    case 0xA866: trap_info.name = "_StuffHex"; break;
    case 0xA867: trap_info.name = "_LongMul"; break;
    case 0xA868: trap_info.name = "_FixMul"; break;
    case 0xA869: trap_info.name = "_FixRatio"; break;
    case 0xA86A: trap_info.name = "_HiWord"; break;
    case 0xA86B: trap_info.name = "_LoWord"; break;
    case 0xA86C: trap_info.name = "_FixRound"; break;
    case 0xA86D: trap_info.name = "_InitPort"; break;
    case 0xA86E: trap_info.name = "_InitGraf"; break;
    case 0xA86F: trap_info.name = "_OpenPort"; break;
    case 0xA870: trap_info.name = "_LocalToGlobal"; break;
    case 0xA871: trap_info.name = "_GlobalToLocal"; break;
    case 0xA872: trap_info.name = "_GrafDevice"; break;
    case 0xA873: trap_info.name = "_SetPort"; break;
    case 0xA874: trap_info.name = "_GetPort"; break;
    case 0xA875: trap_info.name = "_SetPortBits"; break; // _SetPBits
    case 0xA876: trap_info.name = "_PortSize"; break;
    case 0xA877: trap_info.name = "_MovePortTo"; break;
    case 0xA878: trap_info.name = "_SetOrigin"; break;
    case 0xA879: trap_info.name = "_SetClip"; break;
    case 0xA87A: trap_info.name = "_GetClip"; break;
    case 0xA87B: trap_info.name = "_ClipRect"; break;
    case 0xA87C: trap_info.name = "_BackPat"; break;
    case 0xA87D: trap_info.name = "_ClosePort"; break;
    case 0xA87E: trap_info.name = "_AddPt"; break;
    case 0xA87F: trap_info.name = "_SubPt"; break;
    case 0xA880: trap_info.name = "_SetPt"; break;
    case 0xA881: trap_info.name = "_EqualPt"; break;
    case 0xA882: trap_info.name = "_StdText"; break;
    case 0xA883: trap_info.name = "_DrawChar"; break;
    case 0xA884: trap_info.name = "_DrawString"; break;
    case 0xA885: trap_info.name = "_DrawText"; break;
    case 0xA886: trap_info.name = "_TextWidth"; break;
    case 0xA887: trap_info.name = "_TextFont"; break;
    case 0xA888: trap_info.name = "_TextFace"; break;
    case 0xA889: trap_info.name = "_TextMode"; break;
    case 0xA88A: trap_info.name = "_TextSize"; break;
    case 0xA88B: trap_info.name = "_GetFontInfo"; break;
    case 0xA88C: trap_info.name = "_StringWidth"; break;
    case 0xA88D: trap_info.name = "_CharWidth"; break;
    case 0xA88E: trap_info.name = "_SpaceExtra"; break;
    case 0xA88F: trap_info.name = "_OSDispatch"; break; // _Juggler, _KernelDispatch
    case 0xA890: trap_info.name = "_StdLine"; break;
    case 0xA891: trap_info.name = "_LineTo"; break;
    case 0xA892: trap_info.name = "_Line"; break;
    case 0xA893: trap_info.name = "_MoveTo"; break;
    case 0xA894: trap_info.name = "_Move"; break;
    case 0xA895: trap_info.name = "_ShutDown"; break;
    case 0xA896: trap_info.name = "_HidePen"; break;
    case 0xA897: trap_info.name = "_ShowPen"; break;
    case 0xA898: trap_info.name = "_GetPenState"; break;
    case 0xA899: trap_info.name = "_SetPenState"; break;
    case 0xA89A: trap_info.name = "_GetPen"; break;
    case 0xA89B: trap_info.name = "_PenSize"; break;
    case 0xA89C: trap_info.name = "_PenMode"; break;
    case 0xA89D: trap_info.name = "_PenPat"; break;
    case 0xA89E: trap_info.name = "_PenNormal"; break;
    case 0xA89F: trap_info.name = "_Unimplemented"; break; // _DisableDogCow, _EnableDogCow, _InitDogCow, _Moof
    case 0xA8A0: trap_info.name = "_StdRect"; break;
    case 0xA8A1: trap_info.name = "_FrameRect"; break;
    case 0xA8A2: trap_info.name = "_PaintRect"; break;
    case 0xA8A3: trap_info.name = "_EraseRect"; break;
    case 0xA8A4: trap_info.name = "_InvertRect"; break; // _InverRect
    case 0xA8A5: trap_info.name = "_FillRect"; break;
    case 0xA8A6: trap_info.name = "_EqualRect"; break;
    case 0xA8A7: trap_info.name = "_SetRect"; break;
    case 0xA8A8: trap_info.name = "_OffsetRect"; break;
    case 0xA8A9: trap_info.name = "_InsetRect"; break;
    case 0xA8AA: trap_info.name = "_SectRect"; break;
    case 0xA8AB: trap_info.name = "_UnionRect"; break;
    case 0xA8AC: trap_info.name = "_Pt2Rect"; break;
    case 0xA8AD: trap_info.name = "_PtInRect"; break;
    case 0xA8AE: trap_info.name = "_EmptyRect"; break;
    case 0xA8AF: trap_info.name = "_StdRRect"; break;
    case 0xA8B0: trap_info.name = "_FrameRoundRect"; break;
    case 0xA8B1: trap_info.name = "_PaintRoundRect"; break;
    case 0xA8B2: trap_info.name = "_EraseRoundRect"; break;
    case 0xA8B3: trap_info.name = "_InvertRoundRect"; break; // _InverRoundRect
    case 0xA8B4: trap_info.name = "_FillRoundRect"; break;
    case 0xA8B5: trap_info.name = "_ScriptUtil"; break;
    case 0xA8B6: trap_info.name = "_StdOval"; break;
    case 0xA8B7: trap_info.name = "_FrameOval"; break;
    case 0xA8B8: trap_info.name = "_PaintOval"; break;
    case 0xA8B9: trap_info.name = "_EraseOval"; break;
    case 0xA8BA: trap_info.name = "_InvertOval"; break;
    case 0xA8BB: trap_info.name = "_FillOval"; break;
    case 0xA8BC: trap_info.name = "_SlopeFromAngle"; break;
    case 0xA8BD: trap_info.name = "_StdArc"; break;
    case 0xA8BE: trap_info.name = "_FrameArc"; break;
    case 0xA8BF: trap_info.name = "_PaintArc"; break;
    case 0xA8C0: trap_info.name = "_EraseArc"; break;
    case 0xA8C1: trap_info.name = "_InvertArc"; break;
    case 0xA8C2: trap_info.name = "_FillArc"; break;
    case 0xA8C3: trap_info.name = "_PtToAngle"; break;
    case 0xA8C4: trap_info.name = "_AngleFromSlope"; break;
    case 0xA8C5: trap_info.name = "_StdPoly"; break;
    case 0xA8C6: trap_info.name = "_FramePoly"; break;
    case 0xA8C7: trap_info.name = "_PaintPoly"; break;
    case 0xA8C8: trap_info.name = "_ErasePoly"; break;
    case 0xA8C9: trap_info.name = "_InvertPoly"; break;
    case 0xA8CA: trap_info.name = "_FillPoly"; break;
    case 0xA8CB: trap_info.name = "_OpenPoly"; break;
    case 0xA8CC: trap_info.name = "_ClosePoly"; break; // _ClosePgon
    case 0xA8CD: trap_info.name = "_KillPoly"; break;
    case 0xA8CE: trap_info.name = "_OffsetPoly"; break;
    case 0xA8CF: trap_info.name = "_PackBits"; break;
    case 0xA8D0: trap_info.name = "_UnpackBits"; break;
    case 0xA8D1: trap_info.name = "_StdRgn"; break;
    case 0xA8D2: trap_info.name = "_FrameRgn"; break;
    case 0xA8D3: trap_info.name = "_PaintRgn"; break;
    case 0xA8D4: trap_info.name = "_EraseRgn"; break;
    case 0xA8D5: trap_info.name = "_InvertRgn"; break; // _InverRgn
    case 0xA8D6: trap_info.name = "_FillRgn"; break;
    case 0xA8D7: trap_info.name = "_BitMapToRegion"; break; // _BitMapRgn
    case 0xA8D8: trap_info.name = "_NewRgn"; break;
    case 0xA8D9: trap_info.name = "_DisposeRgn"; break; // _DisposRgn
    case 0xA8DA: trap_info.name = "_OpenRgn"; break;
    case 0xA8DB: trap_info.name = "_CloseRgn"; break;
    case 0xA8DC: trap_info.name = "_CopyRgn"; break;
    case 0xA8DD: trap_info.name = "_SetEmptyRgn"; break;
    case 0xA8DE: trap_info.name = "_SetRectRgn"; break; // _SetRecRgn
    case 0xA8DF: trap_info.name = "_RectRgn"; break;
    case 0xA8E0: trap_info.name = "_OffsetRgn"; break; // _OfsetRgn
    case 0xA8E1: trap_info.name = "_InsetRgn"; break;
    case 0xA8E2: trap_info.name = "_EmptyRgn"; break;
    case 0xA8E3: trap_info.name = "_EqualRgn"; break;
    case 0xA8E4: trap_info.name = "_SectRgn"; break;
    case 0xA8E5: trap_info.name = "_UnionRgn"; break;
    case 0xA8E6: trap_info.name = "_DiffRgn"; break;
    case 0xA8E7: trap_info.name = "_XorRgn"; break; // _XOrRgn
    case 0xA8E8: trap_info.name = "_PtInRgn"; break;
    case 0xA8E9: trap_info.name = "_RectInRgn"; break;
    case 0xA8EA: trap_info.name = "_SetStdProcs"; break;
    case 0xA8EB: trap_info.name = "_StdBits"; break;
    case 0xA8EC: trap_info.name = "_CopyBits"; break;
    case 0xA8ED: trap_info.name = "_StdTxMeas"; break;
    case 0xA8EE: trap_info.name = "_StdGetPic"; break;
    case 0xA8EF: trap_info.name = "_ScrollRect"; break;
    case 0xA8F0: trap_info.name = "_StdPutPic"; break;
    case 0xA8F1: trap_info.name = "_StdComment"; break;
    case 0xA8F2: trap_info.name = "_PicComment"; break;
    case 0xA8F3: trap_info.name = "_OpenPicture"; break;
    case 0xA8F4: trap_info.name = "_ClosePicture"; break;
    case 0xA8F5: trap_info.name = "_KillPicture"; break;
    case 0xA8F6: trap_info.name = "_DrawPicture"; break;
    case 0xA8F7: trap_info.name = "_Layout"; break;
    case 0xA8F8: trap_info.name = "_ScalePt"; break;
    case 0xA8F9: trap_info.name = "_MapPt"; break;
    case 0xA8FA: trap_info.name = "_MapRect"; break;
    case 0xA8FB: trap_info.name = "_MapRgn"; break;
    case 0xA8FC: trap_info.name = "_MapPoly"; break;
    case 0xA8FD: trap_info.name = "_PrGlue"; break;
    case 0xA8FE: trap_info.name = "_InitFonts"; break;
    case 0xA8FF: trap_info.name = "_GetFontName"; break; // _GetFName
    case 0xA900: trap_info.name = "_GetFNum"; break;
    case 0xA901: trap_info.name = "_FMSwapFont"; break;
    case 0xA902: trap_info.name = "_RealFont"; break;
    case 0xA903: trap_info.name = "_SetFontLock"; break;
    case 0xA904: trap_info.name = "_DrawGrowIcon"; break;
    case 0xA905: trap_info.name = "_DragGrayRgn"; break;
    case 0xA906: trap_info.name = "_NewString"; break;
    case 0xA907: trap_info.name = "_SetString"; break;
    case 0xA908: trap_info.name = "_ShowHide"; break;
    case 0xA909: trap_info.name = "_CalcVis"; break;
    case 0xA90A: trap_info.name = "_CalcVisBehind"; break; // _CalcVBehind
    case 0xA90B: trap_info.name = "_ClipAbove"; break;
    case 0xA90C: trap_info.name = "_PaintOne"; break;
    case 0xA90D: trap_info.name = "_PaintBehind"; break;
    case 0xA90E: trap_info.name = "_SaveOld"; break;
    case 0xA90F: trap_info.name = "_DrawNew"; break;
    case 0xA910: trap_info.name = "_GetWMgrPort"; break;
    case 0xA911: trap_info.name = "_CheckUpdate"; break; // _CheckUpDate
    case 0xA912: trap_info.name = "_InitWindows"; break;
    case 0xA913: trap_info.name = "_NewWindow"; break;
    case 0xA914: trap_info.name = "_DisposeWindow"; break; // _DisposWindow
    case 0xA915: trap_info.name = "_ShowWindow"; break;
    case 0xA916: trap_info.name = "_HideWindow"; break;
    case 0xA917: trap_info.name = "_GetWRefCon"; break;
    case 0xA918: trap_info.name = "_SetWRefCon"; break;
    case 0xA919: trap_info.name = "_GetWTitle"; break;
    case 0xA91A: trap_info.name = "_SetWTitle"; break;
    case 0xA91B: trap_info.name = "_MoveWindow"; break;
    case 0xA91C: trap_info.name = "_HiliteWindow"; break;
    case 0xA91D: trap_info.name = "_SizeWindow"; break;
    case 0xA91E: trap_info.name = "_TrackGoAway"; break;
    case 0xA91F: trap_info.name = "_SelectWindow"; break;
    case 0xA920: trap_info.name = "_BringToFront"; break;
    case 0xA921: trap_info.name = "_SendBehind"; break;
    case 0xA922: trap_info.name = "_BeginUpdate"; break; // _BeginUpDate
    case 0xA923: trap_info.name = "_EndUpdate"; break; // _EndUpDate
    case 0xA924: trap_info.name = "_FrontWindow"; break;
    case 0xA925: trap_info.name = "_DragWindow"; break;
    case 0xA926: trap_info.name = "_DragTheRgn"; break;
    case 0xA927: trap_info.name = "_InvalRgn"; break;
    case 0xA928: trap_info.name = "_InvalRect"; break;
    case 0xA929: trap_info.name = "_ValidRgn"; break;
    case 0xA92A: trap_info.name = "_ValidRect"; break;
    case 0xA92B: trap_info.name = "_GrowWindow"; break;
    case 0xA92C: trap_info.name = "_FindWindow"; break;
    case 0xA92D: trap_info.name = "_CloseWindow"; break;
    case 0xA92E: trap_info.name = "_SetWindowPic"; break;
    case 0xA92F: trap_info.name = "_GetWindowPic"; break;
    case 0xA930: trap_info.name = "_InitMenus"; break;
    case 0xA931: trap_info.name = "_NewMenu"; break;
    case 0xA932: trap_info.name = "_DisposeMenu"; break; // _DisposMenu
    case 0xA933: trap_info.name = "_AppendMenu"; break;
    case 0xA934: trap_info.name = "_ClearMenuBar"; break;
    case 0xA935: trap_info.name = "_InsertMenu"; break;
    case 0xA936: trap_info.name = "_DeleteMenu"; break;
    case 0xA937: trap_info.name = "_DrawMenuBar"; break;
    case 0xA938: trap_info.name = "_HiliteMenu"; break;
    case 0xA939: trap_info.name = "_EnableItem"; break;
    case 0xA93A: trap_info.name = "_DisableItem"; break;
    case 0xA93B: trap_info.name = "_GetMenuBar"; break;
    case 0xA93C: trap_info.name = "_SetMenuBar"; break;
    case 0xA93D: trap_info.name = "_MenuSelect"; break;
    case 0xA93E: trap_info.name = "_MenuKey"; break;
    case 0xA93F: trap_info.name = "_GetItemIcon"; break; // _GetItmIcon
    case 0xA940: trap_info.name = "_SetItemIcon"; break; // _SetItmIcon
    case 0xA941: trap_info.name = "_GetItemStyle"; break; // _GetItmStyle
    case 0xA942: trap_info.name = "_SetItemStyle"; break; // _SetItmStyle
    case 0xA943: trap_info.name = "_GetItemMark"; break; // _GetItmMark
    case 0xA944: trap_info.name = "_SetItemMark"; break; // _SetItmMark
    case 0xA945: trap_info.name = "_CheckMenuItem"; break; // _CheckItem
    case 0xA946: trap_info.name = "_GetMenuItemText"; break; // _GetItem
    case 0xA947: trap_info.name = "_SetMenuItemText"; break; // _SetItem
    case 0xA948: trap_info.name = "_CalcMenuSize"; break;
    case 0xA949: trap_info.name = "_GetMenuHandle"; break; // _GetMHandle
    case 0xA94A: trap_info.name = "_SetMenuFlashCount"; break; // _SetMenuFlash, _SetMFlash
    case 0xA94B: trap_info.name = "_PlotIcon"; break;
    case 0xA94C: trap_info.name = "_FlashMenuBar"; break;
    case 0xA94D: trap_info.name = "_AppendResMenu"; break; // _AddResMenu
    case 0xA94E: trap_info.name = "_PinRect"; break;
    case 0xA94F: trap_info.name = "_DeltaPoint"; break;
    case 0xA950: trap_info.name = "_CountMenuItems"; break; // _CountMItems
    case 0xA951: trap_info.name = "_InsertResMenu"; break;
    case 0xA952: trap_info.name = "_DeleteMenuItem"; break; // _DelMenuItem
    case 0xA953: trap_info.name = "_UpdateControls"; break; // _UpdtControl
    case 0xA954: trap_info.name = "_NewControl"; break;
    case 0xA955: trap_info.name = "_DisposeControl"; break; // _DisposControl
    case 0xA956: trap_info.name = "_KillControls"; break;
    case 0xA957: trap_info.name = "_ShowControl"; break;
    case 0xA958: trap_info.name = "_HideControl"; break;
    case 0xA959: trap_info.name = "_MoveControl"; break;
    case 0xA95A: trap_info.name = "_GetControlReference"; break; // _GetCRefCon
    case 0xA95B: trap_info.name = "_SetControlReference"; break; // _SetCRefCon
    case 0xA95C: trap_info.name = "_SizeControl"; break;
    case 0xA95D: trap_info.name = "_HiliteControl"; break;
    case 0xA95E: trap_info.name = "_GetControlTitle"; break; // _GetCTitle
    case 0xA95F: trap_info.name = "_SetControlTitle"; break; // _SetCTitle
    case 0xA960: trap_info.name = "_GetControlValue"; break; // _GetCtlValue
    case 0xA961: trap_info.name = "_GetControlMinimum"; break; // _GetMinCtl
    case 0xA962: trap_info.name = "_GetControlMaximum"; break; // _GetMaxCtl
    case 0xA963: trap_info.name = "_SetControlValue"; break; // _SetCtlValue
    case 0xA964: trap_info.name = "_SetControlMinimum"; break; // _SetMinCtl
    case 0xA965: trap_info.name = "_SetControlMaximum"; break; // _SetMaxCtl
    case 0xA966: trap_info.name = "_TestControl"; break;
    case 0xA967: trap_info.name = "_DragControl"; break;
    case 0xA968: trap_info.name = "_TrackControl"; break;
    case 0xA969: trap_info.name = "_DrawControls"; break;
    case 0xA96A: trap_info.name = "_GetControlAction"; break; // _GetCtlAction
    case 0xA96B: trap_info.name = "_SetControlAction"; break; // _SetCtlAction
    case 0xA96C: trap_info.name = "_FindControl"; break;
    case 0xA96D: trap_info.name = "_Draw1Control"; break;
    case 0xA96E: trap_info.name = "_Dequeue"; break; // _DeQueue
    case 0xA96F: trap_info.name = "_Enqueue"; break; // _EnQueue
    case 0xA970: trap_info.name = "_GetNextEvent"; break;
    case 0xA971: trap_info.name = "_EventAvail"; break;
    case 0xA972: trap_info.name = "_GetMouse"; break;
    case 0xA973: trap_info.name = "_StillDown"; break;
    case 0xA974: trap_info.name = "_Button"; break;
    case 0xA975: trap_info.name = "_TickCount"; break;
    case 0xA976: trap_info.name = "_GetKeys"; break;
    case 0xA977: trap_info.name = "_WaitMouseUp"; break;
    case 0xA978: trap_info.name = "_UpdateDialog"; break; // _UpdtDialog
    case 0xA979: trap_info.name = "_CouldDialog"; break;
    case 0xA97A: trap_info.name = "_FreeDialog"; break;
    case 0xA97B: trap_info.name = "_InitDialogs"; break;
    case 0xA97C: trap_info.name = "_GetNewDialog"; break;
    case 0xA97D: trap_info.name = "_NewDialog"; break;
    case 0xA97E: trap_info.name = "_SelectDialogItemText"; break; // _SelIText
    case 0xA97F: trap_info.name = "_IsDialogEvent"; break;
    case 0xA980: trap_info.name = "_DialogSelect"; break;
    case 0xA981: trap_info.name = "_DrawDialog"; break;
    case 0xA982: trap_info.name = "_CloseDialog"; break;
    case 0xA983: trap_info.name = "_DisposeDialog"; break; // _DisposDialog
    case 0xA984: trap_info.name = "_FindDialogItem"; break; // _FindDItem
    case 0xA985: trap_info.name = "_Alert"; break;
    case 0xA986: trap_info.name = "_StopAlert"; break;
    case 0xA987: trap_info.name = "_NoteAlert"; break;
    case 0xA988: trap_info.name = "_CautionAlert"; break;
    case 0xA989: trap_info.name = "_CouldAlert"; break;
    case 0xA98A: trap_info.name = "_FreeAlert"; break;
    case 0xA98B: trap_info.name = "_ParamText"; break;
    case 0xA98C: trap_info.name = "_ErrorSound"; break;
    case 0xA98D: trap_info.name = "_GetDialogItem"; break; // _GetDItem
    case 0xA98E: trap_info.name = "_SetDialogItem"; break; // _SetDItem
    case 0xA98F: trap_info.name = "_SetDialogItemText"; break; // _SetIText
    case 0xA990: trap_info.name = "_GetDialogItemText"; break; // _GetIText
    case 0xA991: trap_info.name = "_ModalDialog"; break;
    case 0xA992: trap_info.name = "_DetachResource"; break;
    case 0xA993: trap_info.name = "_SetResPurge"; break;
    case 0xA994: trap_info.name = "_CurResFile"; break;
    case 0xA995: trap_info.name = "_InitResources"; break;
    case 0xA996: trap_info.name = "_RsrcZoneInit"; break;
    case 0xA997: trap_info.name = "_OpenResFile"; break;
    case 0xA998: trap_info.name = "_UseResFile"; break;
    case 0xA999: trap_info.name = "_UpdateResFile"; break;
    case 0xA99A: trap_info.name = "_CloseResFile"; break;
    case 0xA99B: trap_info.name = "_SetResLoad"; break;
    case 0xA99C: trap_info.name = "_CountResources"; break;
    case 0xA99D: trap_info.name = "_GetIndResource"; break;
    case 0xA99E: trap_info.name = "_CountTypes"; break;
    case 0xA99F: trap_info.name = "_GetIndType"; break;
    case 0xA9A0: trap_info.name = "_GetResource"; break;
    case 0xA9A1: trap_info.name = "_GetNamedResource"; break;
    case 0xA9A2: trap_info.name = "_LoadResource"; break;
    case 0xA9A3: trap_info.name = "_ReleaseResource"; break;
    case 0xA9A4: trap_info.name = "_HomeResFile"; break;
    case 0xA9A5: trap_info.name = "_GetResourceSizeOnDisk"; break; // _SizeRsrc
    case 0xA9A6: trap_info.name = "_GetResAttrs"; break;
    case 0xA9A7: trap_info.name = "_SetResAttrs"; break;
    case 0xA9A8: trap_info.name = "_GetResInfo"; break;
    case 0xA9A9: trap_info.name = "_SetResInfo"; break;
    case 0xA9AA: trap_info.name = "_ChangedResource"; break;
    case 0xA9AB: trap_info.name = "_AddResource"; break;
    case 0xA9AC: trap_info.name = "_AddReference"; break;
    case 0xA9AD: trap_info.name = "_RemoveResource"; break; // _RmveResource
    case 0xA9AE: trap_info.name = "_RmveReference"; break;
    case 0xA9AF: trap_info.name = "_ResError"; break;
    case 0xA9B0: trap_info.name = "_WriteResource"; break;
    case 0xA9B1: trap_info.name = "_CreateResFile"; break;
    case 0xA9B2: trap_info.name = "_SystemEvent"; break;
    case 0xA9B3: trap_info.name = "_SystemClick"; break;
    case 0xA9B4: trap_info.name = "_SystemTask"; break;
    case 0xA9B5: trap_info.name = "_SystemMenu"; break;
    case 0xA9B6: trap_info.name = "_OpenDeskAcc"; break;
    case 0xA9B7: trap_info.name = "_CloseDeskAcc"; break;
    case 0xA9B8: trap_info.name = "_GetPattern"; break;
    case 0xA9B9: trap_info.name = "_GetCursor"; break;
    case 0xA9BA: trap_info.name = "_GetString"; break;
    case 0xA9BB: trap_info.name = "_GetIcon"; break;
    case 0xA9BC: trap_info.name = "_GetPicture"; break;
    case 0xA9BD: trap_info.name = "_GetNewWindow"; break;
    case 0xA9BE: trap_info.name = "_GetNewControl"; break;
    case 0xA9BF: trap_info.name = "_GetMenu"; break; // _GetRMenu
    case 0xA9C0: trap_info.name = "_GetNewMBar"; break;
    case 0xA9C1: trap_info.name = "_UniqueID"; break;
    case 0xA9C2: trap_info.name = "_SystemEdit"; break; // _SysEdit
    case 0xA9C3: trap_info.name = "_KeyTranslate"; break; // _KeyTrans
    case 0xA9C4: trap_info.name = "_OpenRFPerm"; break;
    case 0xA9C5: trap_info.name = "_RsrcMapEntry"; break;
    case 0xA9C6: trap_info.name = "_SecondsToDate"; break; // _Secs2Date, _SecsToDate
    case 0xA9C7: trap_info.name = "_DateToSeconds"; break; // _Date2Secs, _DateToSecs
    case 0xA9C8: trap_info.name = "_SysBeep"; break;
    case 0xA9C9: trap_info.name = "_SysError"; break;
    case 0xA9CA: trap_info.name = "_PutIcon"; break;
    case 0xA9CB: trap_info.name = "_TEGetText"; break;
    case 0xA9CC: trap_info.name = "_TEInit"; break;
    case 0xA9CD: trap_info.name = "_TEDispose"; break;
    case 0xA9CE: trap_info.name = "_TETextBox"; break; // _TextBox
    case 0xA9CF: trap_info.name = "_TESetText"; break;
    case 0xA9D0: trap_info.name = "_TECalText"; break;
    case 0xA9D1: trap_info.name = "_TESetSelect"; break;
    case 0xA9D2: trap_info.name = "_TENew"; break;
    case 0xA9D3: trap_info.name = "_TEUpdate"; break;
    case 0xA9D4: trap_info.name = "_TEClick"; break;
    case 0xA9D5: trap_info.name = "_TECopy"; break;
    case 0xA9D6: trap_info.name = "_TECut"; break;
    case 0xA9D7: trap_info.name = "_TEDelete"; break;
    case 0xA9D8: trap_info.name = "_TEActivate"; break;
    case 0xA9D9: trap_info.name = "_TEDeactivate"; break;
    case 0xA9DA: trap_info.name = "_TEIdle"; break;
    case 0xA9DB: trap_info.name = "_TEPaste"; break;
    case 0xA9DC: trap_info.name = "_TEKey"; break;
    case 0xA9DD: trap_info.name = "_TEScroll"; break;
    case 0xA9DE: trap_info.name = "_TEInsert"; break;
    case 0xA9DF: trap_info.name = "_TESetAlignment"; break; // _TESetJust
    case 0xA9E0: trap_info.name = "_Munger"; break;
    case 0xA9E1: trap_info.name = "_HandToHand"; break;
    case 0xA9E2: trap_info.name = "_PtrToXHand"; break;
    case 0xA9E3: trap_info.name = "_PtrToHand"; break;
    case 0xA9E4: trap_info.name = "_HandAndHand"; break;
    case 0xA9E5: trap_info.name = "_InitPack"; break;
    case 0xA9E6: trap_info.name = "_InitAllPacks"; break;
    case 0xA9E7: trap_info.name = "_Pack0"; break;
    case 0xA9E8: trap_info.name = "_Pack1"; break;
    case 0xA9E9: trap_info.name = "_Pack2"; break;
    case 0xA9EA: trap_info.name = "_Pack3"; break;
    case 0xA9EB: trap_info.name = "_FP68K"; break; // _Pack4
    case 0xA9EC: trap_info.name = "_Elems68K"; break; // _Pack5
    case 0xA9ED: trap_info.name = "_Pack6"; break;
    case 0xA9EE: trap_info.name = "_DecStr68K"; break; // _Pack7, _DECSTR68K
    case 0xA9EF: trap_info.name = "_PtrAndHand"; break;
    case 0xA9F0: trap_info.name = "_LoadSeg"; break;
    case 0xA9F1: trap_info.name = "_UnloadSeg"; break; // _UnLoadSeg
    case 0xA9F2: trap_info.name = "_LaunchApplication"; break; // _Launch
    case 0xA9F3: trap_info.name = "_Chain"; break;
    case 0xA9F4: trap_info.name = "_ExitToShell"; break;
    case 0xA9F5: trap_info.name = "_GetAppParms"; break;
    case 0xA9F6: trap_info.name = "_GetResFileAttrs"; break;
    case 0xA9F7: trap_info.name = "_SetResFileAttrs"; break;
    case 0xA9F8: trap_info.name = "_MethodDispatch"; break;
    case 0xA9F9: trap_info.name = "_InfoScrap"; break;
    case 0xA9FA: trap_info.name = "_UnloadScrap"; break; // _UnlodeScrap
    case 0xA9FB: trap_info.name = "_LoadScrap"; break; // _LodeScrap
    case 0xA9FC: trap_info.name = "_ZeroScrap"; break;
    case 0xA9FD: trap_info.name = "_GetScrap"; break;
    case 0xA9FE: trap_info.name = "_PutScrap"; break;
    case 0xA9FF: trap_info.name = "_Debugger"; break;
    case 0xAA00: trap_info.name = "_OpenCPort"; break;
    case 0xAA01: trap_info.name = "_InitCPort"; break;
    case 0xAA02: trap_info.name = "_CloseCPort"; break;
    case 0xAA03: trap_info.name = "_NewPixMap"; break;
    case 0xAA04: trap_info.name = "_DisposePixMap"; break; // _DisposPixMap
    case 0xAA05: trap_info.name = "_CopyPixMap"; break;
    case 0xAA06: trap_info.name = "_SetPortPix"; break; // _SetCPortPix
    case 0xAA07: trap_info.name = "_NewPixPat"; break;
    case 0xAA08: trap_info.name = "_DisposePixPat"; break; // _DisposPixPat
    case 0xAA09: trap_info.name = "_CopyPixPat"; break;
    case 0xAA0A: trap_info.name = "_PenPixPat"; break;
    case 0xAA0B: trap_info.name = "_BackPixPat"; break;
    case 0xAA0C: trap_info.name = "_GetPixPat"; break;
    case 0xAA0D: trap_info.name = "_MakeRGBPat"; break;
    case 0xAA0E: trap_info.name = "_FillCRect"; break;
    case 0xAA0F: trap_info.name = "_FillCOval"; break;
    case 0xAA10: trap_info.name = "_FillCRoundRect"; break;
    case 0xAA11: trap_info.name = "_FillCArc"; break;
    case 0xAA12: trap_info.name = "_FillCRgn"; break;
    case 0xAA13: trap_info.name = "_FillCPoly"; break;
    case 0xAA14: trap_info.name = "_RGBForeColor"; break;
    case 0xAA15: trap_info.name = "_RGBBackColor"; break;
    case 0xAA16: trap_info.name = "_SetCPixel"; break;
    case 0xAA17: trap_info.name = "_GetCPixel"; break;
    case 0xAA18: trap_info.name = "_GetCTable"; break;
    case 0xAA19: trap_info.name = "_GetForeColor"; break;
    case 0xAA1A: trap_info.name = "_GetBackColor"; break;
    case 0xAA1B: trap_info.name = "_GetCCursor"; break;
    case 0xAA1C: trap_info.name = "_SetCCursor"; break;
    case 0xAA1D: trap_info.name = "_AllocCursor"; break;
    case 0xAA1E: trap_info.name = "_GetCIcon"; break;
    case 0xAA1F: trap_info.name = "_PlotCIcon"; break;
    case 0xAA20: trap_info.name = "_OpenCPicture"; break;
    case 0xAA21: trap_info.name = "_OpColor"; break;
    case 0xAA22: trap_info.name = "_HiliteColor"; break;
    case 0xAA23: trap_info.name = "_CharExtra"; break;
    case 0xAA24: trap_info.name = "_DisposeCTable"; break; // _DisposCTable
    case 0xAA25: trap_info.name = "_DisposeCIcon"; break; // _DisposCIcon
    case 0xAA26: trap_info.name = "_DisposeCCursor"; break; // _DisposCCursor
    case 0xAA27: trap_info.name = "_GetMaxDevice"; break;
    case 0xAA28: trap_info.name = "_GetCTSeed"; break;
    case 0xAA29: trap_info.name = "_GetDeviceList"; break;
    case 0xAA2A: trap_info.name = "_GetMainDevice"; break;
    case 0xAA2B: trap_info.name = "_GetNextDevice"; break;
    case 0xAA2C: trap_info.name = "_TestDeviceAttribute"; break;
    case 0xAA2D: trap_info.name = "_SetDeviceAttribute"; break;
    case 0xAA2E: trap_info.name = "_InitGDevice"; break;
    case 0xAA2F: trap_info.name = "_NewGDevice"; break;
    case 0xAA30: trap_info.name = "_DisposeGDevice"; break; // _DisposGDevice
    case 0xAA31: trap_info.name = "_SetGDevice"; break;
    case 0xAA32: trap_info.name = "_GetGDevice"; break;
    case 0xAA33: trap_info.name = "_Color2Index"; break;
    case 0xAA34: trap_info.name = "_Index2Color"; break;
    case 0xAA35: trap_info.name = "_InvertColor"; break;
    case 0xAA36: trap_info.name = "_RealColor"; break;
    case 0xAA37: trap_info.name = "_GetSubTable"; break;
    case 0xAA38: trap_info.name = "_UpdatePixMap"; break;
    case 0xAA39: trap_info.name = "_MakeITable"; break;
    case 0xAA3A: trap_info.name = "_AddSearch"; break;
    case 0xAA3B: trap_info.name = "_AddComp"; break;
    case 0xAA3C: trap_info.name = "_SetClientID"; break;
    case 0xAA3D: trap_info.name = "_ProtectEntry"; break;
    case 0xAA3E: trap_info.name = "_ReserveEntry"; break;
    case 0xAA3F: trap_info.name = "_SetEntries"; break;
    case 0xAA40: trap_info.name = "_QDError"; break;
    case 0xAA41: trap_info.name = "_SetWinColor"; break;
    case 0xAA42: trap_info.name = "_GetAuxWin"; break;
    case 0xAA43: trap_info.name = "_SetControlColor"; break; // _SetCtlColor
    case 0xAA44: trap_info.name = "_GetAuxiliaryControlRecord"; break; // _GetAuxCtl
    case 0xAA45: trap_info.name = "_NewCWindow"; break;
    case 0xAA46: trap_info.name = "_GetNewCWindow"; break;
    case 0xAA47: trap_info.name = "_SetDeskCPat"; break;
    case 0xAA48: trap_info.name = "_GetCWMgrPort"; break;
    case 0xAA49: trap_info.name = "_SaveEntries"; break;
    case 0xAA4A: trap_info.name = "_RestoreEntries"; break;
    case 0xAA4B: trap_info.name = "_NewColorDialog"; break; // _NewCDialog
    case 0xAA4C: trap_info.name = "_DelSearch"; break;
    case 0xAA4D: trap_info.name = "_DelComp"; break;
    case 0xAA4E: trap_info.name = "_SetStdCProcs"; break;
    case 0xAA4F: trap_info.name = "_CalcCMask"; break;
    case 0xAA50: trap_info.name = "_SeedCFill"; break;
    case 0xAA51: trap_info.name = "_CopyDeepMask"; break;
    case 0xAA52: trap_info.name = "_HighLevelFSDispatch"; break; // _HFSPinaforeDispatch
    case 0xAA53: trap_info.name = "_DictionaryDispatch"; break;
    case 0xAA54: trap_info.name = "_TextServicesDispatch"; break; // _TSMDispatch
    case 0xAA55: trap_info.name = "_KobeMgr"; break;
    case 0xAA56: trap_info.name = "_SpeechRecognitionDispatch"; break;
    case 0xAA57: trap_info.name = "_DockingDispatch"; break;
    case 0xAA58: trap_info.name = "_NewKernelDispatch"; break;
    case 0xAA59: trap_info.name = "_MixedModeDispatch"; break;
    case 0xAA5A: trap_info.name = "_CodeFragmentDispatch"; break;
    case 0xAA5B: trap_info.name = "_PBRemoteAccess"; break;
    case 0xAA5C: trap_info.name = "_OCEUtils"; break;
    case 0xAA5D: trap_info.name = "_DigitalSignature"; break;
    case 0xAA5E: trap_info.name = "_TBDispatch"; break; // _OCETBDispatch
    case 0xAA5F: trap_info.name = "_OCEAuthentication"; break; // _Authentication
    case 0xAA60: trap_info.name = "_DeleteMCEntries"; break; // _DelMCEntries
    case 0xAA61: trap_info.name = "_GetMCInfo"; break;
    case 0xAA62: trap_info.name = "_SetMCInfo"; break;
    case 0xAA63: trap_info.name = "_DisposeMCInfo"; break; // _DispMCInfo
    case 0xAA64: trap_info.name = "_GetMCEntry"; break;
    case 0xAA65: trap_info.name = "_SetMCEntries"; break;
    case 0xAA66: trap_info.name = "_MenuChoice"; break;
    case 0xAA67: trap_info.name = "_ModalDialogMenuSetup"; break;
    case 0xAA68: trap_info.name = "_DialogDispatch"; break;
    case 0xAA69: trap_info.name = "_UserNameNotification"; break;
    case 0xAA6A: trap_info.name = "_DeviceMgr"; break;
    case 0xAA6B: trap_info.name = "_PowerPCFuture"; break;
    case 0xAA6C: trap_info.name = "_PenMacMgr"; break;
    case 0xAA6D: trap_info.name = "_LanguageMgr"; break;
    case 0xAA6E: trap_info.name = "_AppleGuideDispatch"; break;
    case 0xAA72: trap_info.name = "_ContextualMenuDispatch"; break;
    case 0xAA73: trap_info.name = "_ControlDispatch"; break;
    case 0xAA74: trap_info.name = "_AppearanceDispatch"; break;
    case 0xAA75: trap_info.name = "_IconServicesDispatch"; break;
    case 0xAA7D: trap_info.name = "_StartupDispatch"; break;
    case 0xAA7E: trap_info.name = "_SysDebugDispatch"; break;
    case 0xAA80: trap_info.name = "_AVLTreeDispatch"; break;
    case 0xAA81: trap_info.name = "_FileMappingDispatch"; break;
    case 0xAA90: trap_info.name = "_InitPalettes"; break;
    case 0xAA91: trap_info.name = "_NewPalette"; break;
    case 0xAA92: trap_info.name = "_GetNewPalette"; break;
    case 0xAA93: trap_info.name = "_DisposePalette"; break;
    case 0xAA94: trap_info.name = "_ActivatePalette"; break;
    case 0xAA95: trap_info.name = "_SetPalette"; break; // _NSetPalette
    case 0xAA96: trap_info.name = "_GetPalette"; break;
    case 0xAA97: trap_info.name = "_PmForeColor"; break; // _PMForeColor
    case 0xAA98: trap_info.name = "_PmBackColor"; break; // _PMBackColor
    case 0xAA99: trap_info.name = "_AnimateEntry"; break;
    case 0xAA9A: trap_info.name = "_AnimatePalette"; break;
    case 0xAA9B: trap_info.name = "_GetEntryColor"; break;
    case 0xAA9C: trap_info.name = "_SetEntryColor"; break;
    case 0xAA9D: trap_info.name = "_GetEntryUsage"; break;
    case 0xAA9E: trap_info.name = "_SetEntryUsage"; break;
    case 0xAA9F: trap_info.name = "_CTab2Palette"; break;
    case 0xAAA0: trap_info.name = "_Palette2CTab"; break;
    case 0xAAA1: trap_info.name = "_CopyPalette"; break;
    case 0xAAA2: trap_info.name = "_PaletteDispatch"; break;
    case 0xAAA3: trap_info.name = "_CodecDispatch"; break;
    case 0xAAA4: trap_info.name = "_AppleSettingsManagerDispatch"; break; // _ALMDispatch
    case 0xAAAA: trap_info.name = "_QuickTimeDispatch"; break;
    case 0xAADB: trap_info.name = "_CursorDeviceDispatch"; break; // _CursorADBDispatch
    case 0xAADD: trap_info.name = "_HumanInterfaceUtilsDispatch"; break;
    case 0xAAEE: trap_info.name = "_AppleScript"; break;
    case 0xAAF0: trap_info.name = "_PCCardDispatch"; break;
    case 0xAAF1: trap_info.name = "_ataManager"; break; // _ATAMgr
    case 0xAAF2: trap_info.name = "_ControlStripDispatch"; break;
    case 0xAAF3: trap_info.name = "_ExpansionBusDispatch"; break; // _ExpansionManager
    case 0xAAF4: trap_info.name = "_InterruptMgr"; break;
    case 0xAAFA: trap_info.name = "_InitApplication"; break;
    case 0xAAFB: trap_info.name = "_CleanupApplication"; break;
    case 0xAAFE: trap_info.name = "_MixedModeMagic"; break;
    case 0xAB00: trap_info.name = "_BitBlt"; break;
    case 0xAB01: trap_info.name = "_BitsToMap"; break;
    case 0xAB02: trap_info.name = "_BitsToPix"; break;
    case 0xAB03: trap_info.name = "_Jackson"; break;
    case 0xAB04: trap_info.name = "_ColorMap"; break;
    case 0xAB05: trap_info.name = "_CopyHandle"; break;
    case 0xAB06: trap_info.name = "_CullPoints"; break;
    case 0xAB07: trap_info.name = "_PutPicByte"; break;
    case 0xAB08: trap_info.name = "_PutPicOp"; break;
    case 0xAB09: trap_info.name = "_DrawArc"; break;
    case 0xAB0A: trap_info.name = "_DrawLine"; break;
    case 0xAB0B: trap_info.name = "_DrawSlab"; break;
    case 0xAB0C: trap_info.name = "_FastSlabMode"; break;
    case 0xAB0D: trap_info.name = "_GetSeek"; break;
    case 0xAB0E: trap_info.name = "_MakeScaleTbl"; break;
    case 0xAB0F: trap_info.name = "_CheckPic"; break;
    case 0xAB10: trap_info.name = "_DoLine"; break;
    case 0xAB11: trap_info.name = "_OldPatToNew"; break;
    case 0xAB12: trap_info.name = "_PackRgn"; break;
    case 0xAB13: trap_info.name = "_PatConvert"; break;
    case 0xAB14: trap_info.name = "_PatDither"; break;
    case 0xAB15: trap_info.name = "_PatExpand"; break;
    case 0xAB16: trap_info.name = "_PInit"; break;
    case 0xAB17: trap_info.name = "_PortToMap"; break;
    case 0xAB18: trap_info.name = "_PushVerb"; break;
    case 0xAB19: trap_info.name = "_PutLine"; break;
    case 0xAB1A: trap_info.name = "_PutOval"; break;
    case 0xAB1B: trap_info.name = "_PutRgn"; break;
    case 0xAB1C: trap_info.name = "_NewTempBuffer"; break;
    case 0xAB1D: trap_info.name = "_QDExtensions"; break;
    case 0xAB1E: trap_info.name = "_DisposeTempBuffer"; break;
    case 0xAB1F: trap_info.name = "_RgnBlit"; break; // _RgnBlt
    case 0xAB20: trap_info.name = "_RgnOp"; break;
    case 0xAB21: trap_info.name = "_RSect"; break;
    case 0xAB22: trap_info.name = "_SeekRgn"; break;
    case 0xAB23: trap_info.name = "_SetFillPat"; break;
    case 0xAB24: trap_info.name = "_SetUpStretch"; break;
    case 0xAB25: trap_info.name = "_SlabMode"; break;
    case 0xAB26: trap_info.name = "_SortPoints"; break;
    case 0xAB27: trap_info.name = "_StretchBits"; break;
    case 0xAB28: trap_info.name = "_StdDevLoop"; break;
    case 0xAB29: trap_info.name = "_TrimRect"; break;
    case 0xAB2A: trap_info.name = "_XorSlab"; break;
    case 0xAB2B: trap_info.name = "_ExTblPtr"; break;
    case 0xAB2D: trap_info.name = "_NewTempHandle"; break;
    case 0xAB2E: trap_info.name = "_PatExTbl"; break;
    case 0xAB30: trap_info.name = "_bMAIN0"; break;
    case 0xAB31: trap_info.name = "_bMAIN1"; break;
    case 0xAB32: trap_info.name = "_bMAIN2"; break;
    case 0xAB33: trap_info.name = "_bMAIN3"; break;
    case 0xAB34: trap_info.name = "_bSETUP8"; break;
    case 0xAB35: trap_info.name = "_bMAIN9"; break;
    case 0xAB36: trap_info.name = "_bSETUP10"; break;
    case 0xAB37: trap_info.name = "_bMAIN11"; break;
    case 0xAB38: trap_info.name = "_bXMAIN8"; break;
    case 0xAB39: trap_info.name = "_bXMAIN9"; break;
    case 0xAB3A: trap_info.name = "_bXMAIN10"; break;
    case 0xAB3B: trap_info.name = "_bXMAIN11"; break;
    case 0xAB3C: trap_info.name = "_bcMain0"; break;
    case 0xAB3D: trap_info.name = "_bcMain1"; break;
    case 0xAB3E: trap_info.name = "_bHilite"; break;
    case 0xAB3F: trap_info.name = "_bcMain3"; break;
    case 0xAB40: trap_info.name = "_bEND0"; break;
    case 0xAB41: trap_info.name = "_bEND1"; break;
    case 0xAB42: trap_info.name = "_bEND2"; break;
    case 0xAB43: trap_info.name = "_bEND3"; break;
    case 0xAB44: trap_info.name = "_bLONG8"; break;
    case 0xAB45: trap_info.name = "_bEND9"; break;
    case 0xAB46: trap_info.name = "_bEND10"; break;
    case 0xAB47: trap_info.name = "_bEND11"; break;
    case 0xAB48: trap_info.name = "_bXLONG8"; break;
    case 0xAB49: trap_info.name = "_bXEND9"; break;
    case 0xAB4A: trap_info.name = "_bXEND10"; break;
    case 0xAB4B: trap_info.name = "_bXEND11"; break;
    case 0xAB4C: trap_info.name = "_bcEnd0"; break;
    case 0xAB4D: trap_info.name = "_bcEnd1"; break;
    case 0xAB4E: trap_info.name = "_bSlowHilite"; break; // _bSloHilite
    case 0xAB4F: trap_info.name = "_bcEnd"; break; // _bcEnd3
    case 0xAB50: trap_info.name = "_bAvg"; break;
    case 0xAB51: trap_info.name = "_bAddPin"; break;
    case 0xAB52: trap_info.name = "_bAddOver"; break;
    case 0xAB53: trap_info.name = "_bSubPin"; break;
    case 0xAB54: trap_info.name = "_bTransparent"; break;
    case 0xAB55: trap_info.name = "_bMax"; break;
    case 0xAB56: trap_info.name = "_bSubOver"; break;
    case 0xAB57: trap_info.name = "_bMin"; break;
    case 0xAB58: trap_info.name = "_bSetup0"; break;
    case 0xAB59: trap_info.name = "_bLeft0"; break;
    case 0xAB5A: trap_info.name = "_rMASK0"; break;
    case 0xAB5B: trap_info.name = "_rMASK1"; break;
    case 0xAB5C: trap_info.name = "_rMASK2"; break;
    case 0xAB5D: trap_info.name = "_rMASK3"; break;
    case 0xAB5E: trap_info.name = "_rMASK8"; break;
    case 0xAB5F: trap_info.name = "_rMASK9"; break;
    case 0xAB60: trap_info.name = "_rMASK10"; break;
    case 0xAB61: trap_info.name = "_rMASK11"; break;
    case 0xAB62: trap_info.name = "_rXMASK8"; break;
    case 0xAB63: trap_info.name = "_rXMASK9"; break;
    case 0xAB64: trap_info.name = "_rXMASK10"; break;
    case 0xAB65: trap_info.name = "_rXMASK11"; break;
    case 0xAB66: trap_info.name = "_rAvg"; break;
    case 0xAB67: trap_info.name = "_rAddPin"; break;
    case 0xAB68: trap_info.name = "_rAddOver"; break;
    case 0xAB69: trap_info.name = "_rSubPin"; break;
    case 0xAB6A: trap_info.name = "_rTransparent"; break;
    case 0xAB6B: trap_info.name = "_rMax"; break;
    case 0xAB6C: trap_info.name = "_rSubOver"; break;
    case 0xAB6D: trap_info.name = "_rMin"; break;
    case 0xAB6E: trap_info.name = "_rcMask0"; break;
    case 0xAB6F: trap_info.name = "_rcMask1"; break;
    case 0xAB70: trap_info.name = "_rSlowHilite"; break; // _rslowHilite
    case 0xAB71: trap_info.name = "_rcMask3"; break;
    case 0xAB72: trap_info.name = "_rHilite"; break;
    case 0xAB73: trap_info.name = "_stMASK0"; break;
    case 0xAB74: trap_info.name = "_stMASK1"; break;
    case 0xAB75: trap_info.name = "_stMASK2"; break;
    case 0xAB76: trap_info.name = "_stMASK3"; break;
    case 0xAB77: trap_info.name = "_stAvg"; break;
    case 0xAB78: trap_info.name = "_stAddPin"; break;
    case 0xAB79: trap_info.name = "_stAddOver"; break;
    case 0xAB7A: trap_info.name = "_stSubPin"; break;
    case 0xAB7B: trap_info.name = "_stTransparent"; break;
    case 0xAB7C: trap_info.name = "_stMax"; break;
    case 0xAB7D: trap_info.name = "_stSubOver"; break;
    case 0xAB7E: trap_info.name = "_stMin"; break;
    case 0xAB7F: trap_info.name = "_stHilite"; break;
    case 0xAB80: trap_info.name = "_slMASK8"; break;
    case 0xAB81: trap_info.name = "_slMASK9"; break;
    case 0xAB82: trap_info.name = "_slMASK10"; break;
    case 0xAB83: trap_info.name = "_slMASK11"; break;
    case 0xAB84: trap_info.name = "_slXMASK8"; break;
    case 0xAB85: trap_info.name = "_slXMASK9"; break;
    case 0xAB86: trap_info.name = "_slXMASK10"; break;
    case 0xAB87: trap_info.name = "_slXMASK11"; break;
    case 0xAB88: trap_info.name = "_slAvg"; break;
    case 0xAB89: trap_info.name = "_slAddPin"; break;
    case 0xAB8A: trap_info.name = "_slAddOver"; break;
    case 0xAB8B: trap_info.name = "_slSubPin"; break;
    case 0xAB8C: trap_info.name = "_slTransparent"; break;
    case 0xAB8D: trap_info.name = "_slMax"; break;
    case 0xAB8E: trap_info.name = "_slSubOver"; break;
    case 0xAB8F: trap_info.name = "_slMin"; break;
    case 0xAB90: trap_info.name = "_slHilite"; break;
    case 0xAB91: trap_info.name = "_ITabMatch"; break;
    case 0xAB92: trap_info.name = "_ColorThing"; break;
    case 0xAB93: trap_info.name = "_Pollack"; break;
    case 0xAB94: trap_info.name = "_AllocRunBuf"; break;
    case 0xAB95: trap_info.name = "_InitRgn"; break;
    case 0xAB96: trap_info.name = "_ScaleBlt"; break;
    case 0xAB97: trap_info.name = "_stNoStack"; break;
    case 0xAB98: trap_info.name = "_BlitCase"; break;
    case 0xAB99: trap_info.name = "_stScanLoop"; break;
    case 0xAB9A: trap_info.name = "_PicItem1"; break;
    case 0xAB9B: trap_info.name = "_MakeGrayITab"; break; // _MakeGrayItab
    case 0xAB9C: trap_info.name = "_FastLine"; break;
    case 0xAB9D: trap_info.name = "_FastSlant"; break;
    case 0xAB9E: trap_info.name = "_BitsDevLoop"; break;
    case 0xABA0: trap_info.name = "_rArith16Tab"; break;
    case 0xABA1: trap_info.name = "_rArith32Tab"; break;
    case 0xABA2: trap_info.name = "_rHiliteTab"; break;
    case 0xABA3: trap_info.name = "_gsRunTbl"; break;
    case 0xABA4: trap_info.name = "_gsExpTbl"; break;
    case 0xABA5: trap_info.name = "_gsSeekTbl"; break;
    case 0xABA6: trap_info.name = "_stArith16Tab"; break;
    case 0xABA7: trap_info.name = "_stArith32Tab"; break;
    case 0xABA8: trap_info.name = "_stColorTab"; break;
    case 0xABA9: trap_info.name = "_stGrayTab"; break;
    case 0xABAA: trap_info.name = "_stSearchTab"; break;
    case 0xABAB: trap_info.name = "_ScaleIndToInd"; break;
    case 0xABAC: trap_info.name = "_scIndTab1"; break;
    case 0xABAD: trap_info.name = "_scIndTab2"; break;
    case 0xABAE: trap_info.name = "_scIndTab4"; break;
    case 0xABAF: trap_info.name = "_scIndTab8"; break;
    case 0xABB0: trap_info.name = "_scIndTab16"; break;
    case 0xABB1: trap_info.name = "_scIndTab32"; break;
    case 0xABB2: trap_info.name = "_scDirTab1"; break;
    case 0xABB3: trap_info.name = "_scDirTab2"; break;
    case 0xABB4: trap_info.name = "_scDirTab4"; break;
    case 0xABB5: trap_info.name = "_scDirTab8"; break;
    case 0xABB6: trap_info.name = "_scDirTab16"; break;
    case 0xABB7: trap_info.name = "_scDirTab32"; break;
    case 0xABB8: trap_info.name = "_bArith16Tab"; break;
    case 0xABB9: trap_info.name = "_bArith32Tab"; break;
    case 0xABBA: trap_info.name = "_bHiliteTab"; break;
    case 0xABBB: trap_info.name = "_bArith16Setup"; break;
    case 0xABBC: trap_info.name = "_bArith32Setup"; break;
    case 0xABBD: trap_info.name = "_slArith16Tab"; break;
    case 0xABBE: trap_info.name = "_slArith32Tab"; break;
    case 0xABBF: trap_info.name = "_32QD"; break;
    case 0xABC0: trap_info.name = "_QDAlphaDispatch"; break;
    case 0xABC1: trap_info.name = "_QDStreamToMask"; break;
    case 0xABC2: trap_info.name = "_QTMatrixMathDispatch"; break;
    case 0xABC3: trap_info.name = "_NQDMisc"; break;
    case 0xABC4: trap_info.name = "_GetPMData"; break;
    case 0xABC5: trap_info.name = "_32QD"; break;
    case 0xABC6: trap_info.name = "_32QD"; break;
    case 0xABC7: trap_info.name = "_32QD"; break;
    case 0xABC8: trap_info.name = "_StdOpcodeProc"; break;
    case 0xABC9: trap_info.name = "_IconDispatch"; break;
    case 0xABCA: trap_info.name = "_DeviceLoop"; break;
    case 0xABCC: trap_info.name = "_PBBlockMove"; break;
    case 0xABCD: trap_info.name = "_SnappingTurk"; break;
    case 0xABCE: trap_info.name = "_UnicodeMgr"; break;
    case 0xABCF: trap_info.name = "_ProcessMgr"; break;
    case 0xABE0: trap_info.name = "_QDExtensions2"; break;
    case 0xABEA: trap_info.name = "_IntModemDispatch"; break; // _ModemMgr
    case 0xABEB: trap_info.name = "_DisplayDispatch"; break;
    case 0xABEC: trap_info.name = "_ButtonMgr"; break;
    case 0xABED: trap_info.name = "_DragDispatch"; break;
    case 0xABEE: trap_info.name = "_ColorSync"; break;
    case 0xABEF: trap_info.name = "_TTSMgr"; break;
    case 0xABF0: trap_info.name = "_AROSE"; break;
    case 0xABF1: trap_info.name = "_GestaltValueDispatch"; break;
    case 0xABF2: trap_info.name = "_ThreadDispatch"; break;
    case 0xABF3: trap_info.name = "_EddyTrap"; break;
    case 0xABF4: trap_info.name = "_XTNDMgr"; break;
    case 0xABF5: trap_info.name = "_DSPManager"; break; // _DSPDispatch
    case 0xABF6: trap_info.name = "_CollectionMgr"; break;
    case 0xABF7: trap_info.name = "_SynchIdleTime"; break;
    case 0xABF8: trap_info.name = "_StdOpcode"; break; // _StdOpcodeProc
    case 0xABF9: trap_info.name = "_AUXDispatch"; break;
    case 0xABFA: trap_info.name = "_AUXSysCall"; break;
    case 0xABFB: trap_info.name = "_MessageMgr"; break;
    case 0xABFC: trap_info.name = "_TranslationDispatch"; break;
    case 0xABFD: trap_info.name = "_TouchStone"; break;
    case 0xABFE: trap_info.name = "_GXPrinting"; break; // _Printing
    case 0xABFF: trap_info.name = "_DebugStr"; break;
    case 0xAC47: trap_info.name = "_NFracCos"; break;
    case 0xAC48: trap_info.name = "_NFracSin"; break;
    case 0xAC49: trap_info.name = "_NFracSqrt"; break;
    case 0xAC4A: trap_info.name = "_NFracMul"; break;
    case 0xAC4B: trap_info.name = "_NFracDiv"; break;
    case 0xAC4D: trap_info.name = "_NFixDiv"; break;
    case 0xFC00: trap_info.name = "_ToolBoxCoprocessorNop"; break;
    case 0xFC01: trap_info.name = "_DecodeSANEop"; break;
    case 0xFC02: trap_info.name = "_ExitSANEop"; break;
    case 0xFC03: trap_info.name = "_LoadArg1Extended"; break;
    case 0xFC04: trap_info.name = "_LoadArg2Convert"; break;
    case 0xFC05: trap_info.name = "_CopyArg2ToArg1"; break;
    case 0xFC06: trap_info.name = "_CheckResultArg1"; break;
    case 0xFC07: trap_info.name = "_StoreArg1Extended"; break;
    case 0xFC08: trap_info.name = "_StoreArg1Double"; break;
    case 0xFC09: trap_info.name = "_StoreArg1Single"; break;
    case 0xFC0A: trap_info.name = "_FloatAdd"; break;
    case 0xFC0B: trap_info.name = "_FloatSub"; break;
    case 0xFC0C: trap_info.name = "_FloatMul"; break;
    case 0xFC0D: trap_info.name = "_FloatDiv"; break;
    case 0xFC0E: trap_info.name = "_FloatRem"; break;
    case 0xFC0F: trap_info.name = "_FloatSqrt"; break;
    case 0xFC10: trap_info.name = "_ATrapOSExit"; break;
    case 0xFC11: trap_info.name = "_ATrapOSNoA0Exit"; break;
    case 0xFC12: trap_info.name = "_MoveBytes"; break;
    case 0xFC13: trap_info.name = "_MoveBytesNoDCBZ"; break;
    case 0xFE00: trap_info.name = "_RiscCoprocessorNop"; break;
    case 0xFE01: trap_info.name = "_CallRoutineDescriptor"; break;
    case 0xFE02: trap_info.name = "_ReturnToNative"; break;
    case 0xFE03: trap_info.name = "_ExecuteRiscContext"; break;
    case 0xFE04: trap_info.name = "_MoveFromECR"; break;
    case 0xFE05: trap_info.name = "_MoveToECR"; break;
    case 0xFE06: trap_info.name = "_EMMUOpTrap"; break; // do VM op, cause a line F instruction if it fails
    case 0xFE07: trap_info.name = "_HandleMixedModeFault"; break;
    case 0xFE08: trap_info.name = "_ReadTimeBase32"; break;
    case 0xFE09: trap_info.name = "_ReadTimeBase64"; break;
    case 0xFE0A: trap_info.name = "_KernelVMDispatch"; break; // EMMUOpCCR // do VM op, set CCR.Z if it fails
    case 0xFEED: trap_info.name = "_MixedMode"; break;
    default: return false;
    }
    return true;
}
